config/routes.rb
# frozen_string_literal: true

ActionController::Base
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: ->(env){
    redirector = if Rails.env.development?
      redirect "http://127.0.0.1:#{ENV['PROXY_PORT']}/web", status: 302
    else
      redirect '/web'
    end
    redirector.call env
  }

  get :'favicon.ico', to: -> (_env) { [404, {}, ''] }

  def json_api(**options, &block)
    (options[:defaults] ||= {})[:format] = :json
    (options[:constraints] ||= {})[:format] = :json
    scope(**options, &block)
  end

  def web_controller(controller, as = nil, &block)
    as ||= controller
    as = as.to_s.gsub '/', '_'
    scope controller, controller: controller, as: as, &block
  end

  def web_resource resource_name, skip: []
    scope resource_name, controller: resource_name, as: resource_name do
      post :/, action: :index unless skip.include? :index
      post :create unless skip.include? :create
      scope ':id' do
        post :/, action: :show unless skip.include? :show
        post :update unless skip.include? :update
        post :archive unless skip.include? :archive
      end
      yield if block_given?
    end
  end

  def web_v2_resource resource_name, skip: []
    scope resource_name, controller: resource_name, as: resource_name do
      post :/, action: :index unless skip.include? :index
      post :create unless skip.include? :create
      scope ':id' do
        post :update unless skip.include? :update
      end
      yield if block_given?
    end
  end

  namespace :public do

    controller :application do
      get :countries
    end

  end # /public

  namespace :admin do

    scope :translations, controller: :translations, as: :translations do
      get :'/edit/:language', action: :edit_language, as: 'edit_language'
      post :'/update/:language', action: :update_language, as: 'update_language'
    end

  end # /admin

  namespace :docs do
    get 'dev/mvp-2022', to: redirect(
      'https://docs.google.com/spreadsheets/d/12XzyYzEsjRExS91n6w86UHmGY4DAAtTQbzeEA4UVomc',
      status: 302
    )
  end

  scope :api, as: :api do

    namespace :web do

      namespace :v2 do
        web_v2_resource :donors
        web_v2_resource :material_kits
        web_v2_resource :users do
          scope ':id' do
            post :change_password
            post :lock
          end
        end
        web_v2_resource :work_agreements
      end

      web_controller :session do
        get :'translations/:language', action: :translations, as: :translations
      end

      json_api do
        web_controller :session do
          post :show
          post :login
          post :logout
        end

        web_resource :countries, skip: %i[show create update destroy]

        web_resource :users do
          scope ':id' do
            post :change_password
            post :lock
          end
        end

        web_resource :projects
        web_resource :courses
        web_resource :standardized_courses
        web_resource :education_levels
        web_resource :location_systems, skip: %i[create show update archive]
        web_resource :locations, skip: %i[create show update archive]
        web_resource :material_kits
        web_resource :groups do
          scope ':id' do
            post :show_schedule
            post :update_schedule
          end
        end
        web_resource :people
        web_resource :schools
        web_resource :school_years
        web_resource :subjects
        web_resource :subject_categories
      end
    end

    namespace :android do
      json_api do
        web_controller :session do
          post :login
          post :logout
        end
      end

      web_controller :uploads do
        post :group_attendance_photos
      end
    end

  end

  namespace :server do
    scope :pdf, controller: :pdf, constraints: { format: :pdf }, defaults: { format: :pdf } do
      get :'group_attendance/:group_id', action: :group_attendance
    end
  end

  # backdoor for tests
  if Rails.env.test?
    get 'authn', to: 'application#test_set_authn'
  end
end

app/controllers/admin/translations_controller.rb
# frozen_string_literal: true

module Admin
  class TranslationsController < ApplicationController

    def edit_language
      csv_lines = []
      TranslationValue.each_translation_csv_row params[:language] do |next_value|
        csv_lines.push next_value
      end
      @language = csv_lines.join "\n"
    end

    def update_language
      language = params[:language]
      csv = params[:csv]&.strip || ''
      TranslationTemplate.create! language: language, csv: csv
      TranslationValue.import_language_from_csv language, csv
      on_translation_changed language
    end

    private

    def on_translation_changed language
      SystemTranslations.create_current! language
      if Rails.env.development?
        path = Rails.root.join "db/translations/#{language}.csv"
        File.open path, 'w' do |f|
          TranslationValue.each_translation_csv_row language do |next_value|
            f.puts next_value
          end
        end
      end
    end

  end
end

app/views/admin/translations/edit_language.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Language</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'admin/application' %>
  <%= javascript_include_tag 'admin/vendor' %>
  <%= csrf_meta_tag %>
</head>
<body class="d-flex flex-column h-100 bg-secondary">

<div class="d-flex justify-content-center p-4">
    <h3 class="me-3">Edit language - <%= params[:language] %></h3>
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#save-confirm-modal">
      Save
    </button>
</div>

<div class="flex-grow-1 mb-4 px-2">
  <textarea class="bg-dark h-100 w-100 border-0 flex-grow-1 text-white" id="language_csv"><%= @language %>&#10;</textarea>
</div>

<div id="save-confirm-modal" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit language - <%= params[:language] %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure to overwrite all the translation for language <%= params[:language] %>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-warning" data-action="save">
          <div class="spinner-border d-none" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
          Save changes
        </button>
      </div>
    </div>
  </div>
</div>

</body>

<script type="module">
    import app from '<%= javascript_path 'admin_app' %>';

    app.run();

    app.actions.add('save', ({ target }) => {
        app.actions.lockButton(target);
        const data = new FormData();
        data.set('csv', app.find('#language_csv')?.value);
        Rails.ajax({
            type: 'POST',
            url: '<%= admin_translations_update_language_path(params[:language]) %>',
            data,
            success () {
                window.location.reload();
            }
        });
    });
</script>
</html>